# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-17 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
